#!/bin/sh
#
#  Copyright 2014 Alcatel-Lucent Enterprise.
#
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
#  except in compliance with the License. You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software distributed under the License
#  is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
#  either express or implied. See the License for the specific language governing permissions
#  and limitations under the License.
#
#
# $File: omniswitch_clear_db$

# $Build: OONP_H_R01_6$

# $Date: 05/06/2014 12:10:39$

# $Author: vapoonat$

#
#

echo "Connecting to mysql database and clearing Omni and OVS table entries..."

mysql <<END_SCRIPT

use quantum;
delete from ovs_network_bindings;
delete from ovs_vlan_allocations;
delete from omni_network_bindings;
delete from omni_vlan_allocations;
delete from ports;
delete from subnets;
delete from networks;
exit



